import { DataTypes, type QueryInterface } from 'sequelize';

/**
 * Migration: Create company table.
 *
 * Companies are the businesses that supply products through providers.
 * - UUID primary key generated by PostgreSQL (no manual conversion needed)
 * - `tax_id` is the RUC (unique business identifier in Peru)
 * - `is_active` enables soft delete without losing historical data
 */
export async function up({ context: queryInterface }: { context: QueryInterface }) {
  await queryInterface.createTable('company', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
    },
    name: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },
    tax_id: {
      type: DataTypes.STRING(25),
      allowNull: false,
      unique: true,
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  });
}

export async function down({ context: queryInterface }: { context: QueryInterface }) {
  await queryInterface.dropTable('company');
}
